name: Hugo-CI
on:
  push:
    branches: [ develop ]
    paths-ignore:
        '.github/**'

jobs:
  job-one:
    name: Deploy
    runs-on: [self-hosted, linux, x64, dev4-page]
    steps:
      - name: hugo build
        run: |
          cd aspose-page-docs